---
title: "pre-assignment"
author: "Jakub Skrajny"
date: "27 04 2021"
output:
  pdf_document: default
  html_document: default
---
# Libraries
```{r}
library(openxlsx)
library(tseries)
library(forecast)
library(EnvStats)
```

# Read data (date = number of days from 1900)
```{r cars}
data <- read.xlsx("Lions_Den_data.xlsx")
timeseries <- unlist(data[2])
dates <- unlist(data[1])
```

# Decomposition
```{r}
ts <- ts(timeseries, frequency = 12)
decompose <- decompose(ts, "additive")
plot(decompose)
decompose$trend
```

# Outliers
Rosner's test suggest that there is only one outlier.
```{r}
hist(timeseries,
  xlab = "coal usage",
)
rosnerTest(timeseries, k = 3)
```

# Autocorrelation and stationarity analysis
We can see that time-series is already stationary.
```{r}
x <- timeseries
#autocorrelation
acf(x, lag.max = 12)
#stationary test
adf.test(x)
```

# Linear regression
```{r}
#trend
x <- as.numeric(decompose$trend)
x <- x[!is.na(x)]
time <- seq(1, length(x))
df <- data.frame(x, time)
model <- lm(x ~ time, data = df)
p <- as.data.frame(seq(length(x)+1, length(x)+12))
colnames(p) <- "time"
trend_prediction <- as.numeric(predict(model, newdata=p))
concat_trend <- c(x, trend_prediction)
plot(concat_trend, type="l")
#seasonal
seasonal_prediction <- as.numeric(tail(decompose$seasonal, n=12))
concat_seasonal <- c(
  as.numeric(decompose$seasonal),
  seasonal_prediction
)
# overall predicion
overall_prediction <- trend_prediction + seasonal_prediction
plot(c(decompose$x, overall_prediction), type="l")
plot(overall_prediction, type="l")
overall_prediction
```